redirectsOrigin = "inline"
headers = []

[functions]

[functions._ipx]
node_bundler = "nft"

[functions.___netlify-handler]
included_files = [".env", ".env.local", ".env.production", ".env.production.local", "./public/locales/**", "./next-i18next.config.js", ".next/server/**", ".next/serverless/**", ".next/*.json", ".next/BUILD_ID", ".next/static/chunks/webpack-middleware*.js", "!.next/server/**/*.js.nft.json", "!.next/server/**/*.map", "!**/node_modules/@next/swc*/**/*", "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*", "!node_modules/next/dist/server/lib/squoosh/**/*.wasm", "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm", "!node_modules/next/dist/compiled/webpack/bundle4.js", "!node_modules/next/dist/compiled/webpack/bundle5.js", "node_modules/styled-jsx/style.js", "!node_modules/sharp/**/*"]
external_node_modules = []
node_bundler = "nft"

[functions.___netlify-odb-handler]
included_files = [".env", ".env.local", ".env.production", ".env.production.local", "./public/locales/**", "./next-i18next.config.js", ".next/server/**", ".next/serverless/**", ".next/*.json", ".next/BUILD_ID", ".next/static/chunks/webpack-middleware*.js", "!.next/server/**/*.js.nft.json", "!.next/server/**/*.map", "!**/node_modules/@next/swc*/**/*", "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*", "!node_modules/next/dist/server/lib/squoosh/**/*.wasm", "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm", "!node_modules/next/dist/compiled/webpack/bundle4.js", "!node_modules/next/dist/compiled/webpack/bundle5.js", "node_modules/styled-jsx/style.js", "!node_modules/sharp/**/*"]
external_node_modules = []
node_bundler = "nft"

[functions."_api_*"]
included_files = [".env", ".env.local", ".env.production", ".env.production.local", "./public/locales/**", "./next-i18next.config.js", ".next/server/**", ".next/serverless/**", ".next/*.json", ".next/BUILD_ID", ".next/static/chunks/webpack-middleware*.js", "!.next/server/**/*.js.nft.json", "!.next/server/**/*.map", "!**/node_modules/@next/swc*/**/*", "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*", "!node_modules/next/dist/server/lib/squoosh/**/*.wasm", "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm", "!node_modules/next/dist/compiled/webpack/bundle4.js", "!node_modules/next/dist/compiled/webpack/bundle5.js", "node_modules/styled-jsx/style.js", "!node_modules/sharp/**/*"]
external_node_modules = []
node_bundler = "nft"

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/home/oc/projects/returncue/.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npx prisma generate && npm run build"

[build.environment]
NODE_VERSION = "20"
NEXTAUTH_URL = "https://returncue.netlify.app"
NEXT_PRIVATE_TARGET = "server"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_next/image*"
to = "/_ipx/w_:width,q_:quality/:url"
status = 301.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/builders/_ipx"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]
Cookie = ["__prerender_bypass", "__next_preview_data"]

[redirects.headers]

[[redirects]]
from = "/_next/data/Nfga_HdtTF61y3vVziHPO/_not-found.json"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_not-found"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]