[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXTAUTH_URL = "https://returncue.netlify.app"

[functions]
  "*"
    node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
